[package]
edition = "2021"
name = "palindrome-products"
version = "1.2.0"

[profile.test]
opt-level = 3
lto="thin"
#lto=true

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3

[dependencies]
